version: '3.0'
services:
    node:
        build:
            context: ./dockerfiles/node
            args:
                - USER=${USER}
                - USER_GID=${USER_GID:-1000}
                - USER_UID=${USER_UID:-1000}
                - API_URL="https://api.anatroc/app_dev.php"
        volumes:
            - ./app:/app
        networks:
            static-network:

    nginx:
        build:
            context: dockerfiles/nginx/node
            args:
                - DNS_FRONT=${DNS_FRONT:-front.anatroc}
        volumes:
            - ./app:/app
        depends_on:
            - node
        links:
            - node
        networks:
            static-network:
                ipv4_address: 172.41.0.10


networks:
    static-network:
        ipam:
            config:
                - subnet: 172.41.0.0/24
